In [34]:
import pandas as pd
import numpy as np

In [22]:
#Creating a table of 25 items with quantities

In [27]:
pd.Series([600,800,1200,3000,300,500,600,700,750,890,450,1100,1300,5000,900,950,870,600,500,1000,250,650,4500,5500,6000],['Paracetamol','Diclofenac','Amoxil' 'Ibuprofen', 'Metformin', 'Glibenclamide', 'Glimepiride', 'Glicazide', 'Cefuroxime', 'Ceftriaxone','Arthemether', 'Arteether inj','Wellwoman', 'Wellman', 'Plaster', 'Bandage', 'Cotton wool', 'Amlodipine', 'Lisinopril', 'Hydrex', 'Vasoprin','Clarthromycin', 'Ciprofloxacin', 'Levofloxacin', 'Ofloxacin','Ketoconazole'])

Paracetamol         600
Diclofenac          800
AmoxilIbuprofen    1200
Metformin          3000
Glibenclamide       300
Glimepiride         500
Glicazide           600
Cefuroxime          700
Ceftriaxone         750
Arthemether         890
Arteether inj       450
Wellwoman          1100
Wellman            1300
Plaster            5000
Bandage             900
Cotton wool         950
Amlodipine          870
Lisinopril          600
Hydrex              500
Vasoprin           1000
Clarthromycin       250
Ciprofloxacin       650
Levofloxacin       4500
Ofloxacin          5500
Ketoconazole       6000
dtype: int64

In [37]:
a= pd.DataFrame(np.random.randn(25,5),columns=["A",'B','C','D','E'])
a

           A         B         C         D         E
0  -0.097179 -0.414474 -0.279760  0.719921  1.314790
1   2.120825  2.302375  1.651028  0.168125  1.547830
2  -1.465623  0.289703  1.477488 -0.903289 -1.180224
3  -0.792578  0.207202  0.394020  0.294206  0.439132
4  -0.815526  0.583357  0.571187 -0.142043  0.552674
5   0.135837 -0.099767 -0.803232 -0.219490  2.230515
6   0.080741 -0.380132 -0.952614  0.611042  2.073094
7  -1.884628  1.764219 -0.128343 -0.401519 -0.177167
8  -0.586765  0.289285  0.343028  1.925183 -0.113049
9  -0.946109  0.415847 -0.675650 -1.088437  1.869595
10 -1.687716  0.061640  0.091187  0.832565  0.724800
11 -0.678968 -1.789067 -0.338100  0.859996 -1.878046
12  0.323814 -1.032458  2.089785  0.110263  1.781672
13  0.502460  0.099040  0.163700  0.498100  1.747688
14 -0.646478  1.646469 -0.723954 -0.957822  2.965854
15 -0.945880 -2.453545 -2.059451 -1.722214  0.662968
16  0.205597 -0.833512  1.509296 -0.987693 -1.122621
17  1.684985  0.950773  0.489624 -0.395607  1.282216
18  0.662949  0.947314 -0.873913  0.532707 -1.007608
19 -0.659981  0.598684 -0.496359  0.374739  1.007283
20  0.287815  0.591115  0.590721  0.621546  0.953801
21  0.448418 -1.054107  0.548683 -1.083837  0.445626
22  1.189270 -0.702304 -0.135754  1.063141 -0.450103
23 -0.977631  0.899766 -1.288712  1.267306 -0.170991
24  0.158253  0.799658 -0.770669  0.418148  1.192162