In [1]:
import seaborn as sns
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("C:\\Users\\user\\Downloads\\Annual_cause_of_death.csv")

In [3]:
df

,Country,Code,Year,Death by executions,Deaths - Meningitis,Deaths - Alzheimer's disease,Deaths - Parkinson's disease,Deaths - Nutritional deficiencies,Deaths - Malaria,Deaths - Drowning,...,Deaths - Chronic kidney disease - Sex: Both - Age: All Ages (Number),Deaths - Poisonings - Sex: Both - Age: All Ages (Number),Deaths - Protein-energy malnutrition - Sex: Both - Age: All Ages (Number),Terrorism (deaths),Deaths - Road injuries - Sex: Both - Age: All Ages (Number),Deaths - Chronic respiratory diseases - Sex: Both - Age: All Ages (Number),Deaths - Cirrhosis and other chronic liver diseases - Sex: Both - Age: All Ages (Number),Deaths - Digestive diseases - Sex: Both - Age: All Ages (Number),"Deaths - Fire, heat, and hot substances - Sex: Both - Age: All Ages (Number)",Deaths - Acute hepatitis - Sex: Both - Age: All Ages (Number)
0,Afghanistan,AFG,2007,15,2933.0,1402.0,450.0,2488.0,393.0,2127.0,...,4490.0,512.0,2439.0,1199.0,7425.0,7222.0,3346.0,6458.0,481.0,3437.0
1,Afghanistan,AFG,2008,17,2731.0,1424.0,455.0,2277.0,255.0,1973.0,...,4534.0,495.0,2231.0,1092.0,7355.0,7143.0,3316.0,6408.0,462.0,3005.0
2,Afghanistan,AFG,2009,0,2460.0,1449.0,460.0,2040.0,239.0,1852.0,...,4597.0,483.0,1998.0,1065.0,7290.0,7045.0,3291.0,6358.0,448.0,2663.0
3,Afghanistan,AFG,2011,2,2327.0,1508.0,473.0,1846.0,390.0,1775.0,...,4785.0,483.0,1805.0,1525.0,7432.0,6916.0,3318.0,6370.0,448.0,2365.0
4,Afghanistan,AFG,2012,14,2254.0,1544.0,482.0,1705.0,94.0,1716.0,...,4846.0,482.0,1667.0,3521.0,7494.0,6878.0,3353.0,6398.0,445.0,2264.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7268,Zimbabwe,ZWE,2015,NaN,1439.0,754.0,215.0,3019.0,2518.0,770.0,...,2108.0,381.0,2990.0,NaN,2373.0,2751.0,1956.0,4202.0,632.0,146.0
7269,Zimbabwe,ZWE,2016,NaN,1457.0,767.0,219.0,3056.0,2050.0,801.0,...,2160.0,393.0,3027.0,NaN,2436.0,2788.0,1962.0,4264.0,648.0,146.0
7270,Zimbabwe,ZWE,2017,NaN,1460.0,781.0,223.0,2990.0,2116.0,818.0,...,2196.0,398.0,2962.0,0.0,2473.0,2818.0,2007.0,4342.0,654.0,144.0
7271,Zimbabwe,ZWE,2018,NaN,1450.0,795.0,227.0,2918.0,2088.0,825.0,...,2240.0,400.0,2890.0,NaN,2509.0,2849.0,2030.0,4377.0,657.0,139.0
7272,Zimbabwe,ZWE,2019,NaN,1450.0,812.0,232.0,2884.0,2068.0,827.0,...,2292.0,405.0,2855.0,NaN,2554.0,2891.0,2065.0,4437.0,662.0,136.0

In [4]:
c=df.rename(columns={'Entity':Country'})

SyntaxError: EOL while scanning string literal (1743236372.py, line 1)

In [ ]:
c

In [ ]:
c

In [ ]:
df

In [ ]:
print(df.columns)

In [ ]:
df.isnull()

In [ ]:
df.isnull().sum()

In [ ]:
df.duplicated()

In [ ]:
df.describe()

In [ ]:
df.dtypes

In [ ]:
df.info

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.drop(["Code","Death by executions"],axis=1)

In [ ]:
df.rename(columns={"Deaths - Meningitis":"Meningitis","Deaths - Alzheimer's disease":"Alzheimer","Deaths - Parkinson's disease":"Parkinson","Deaths - Nutritional deficiencies":"Nutritional Deficiencies",'Deaths - Malaria':'Malaria'},inplace=True)

In [ ]:
c = df.copy()

In [ ]:
c.head(1)